import Foundation
import MLKitTranslate

func TranslateLanguage(from language: String) -> TranslateLanguage? {
    switch language.lowercased() {
    case "afrikaans":
        return .afrikaans
    case "albanian":
        return .albanian
    case "arabic":
        return .arabic
    case "belarusian":
        return .belarusian
    case "bengali":
        return .bengali
    case "bulgarian":
        return .bulgarian
    case "catalan":
        return .catalan
    case "chinese":
        return .chinese
    case "czech":
        return .czech
    case "danish":
        return .danish
    case "dutch":
        return .dutch
    case "english":
        return .english
    case "eperanto":
        return .eperanto
    case "estonian":
        return .estonian
    case "finnish":
        return .finnish
    case "french":
        return .french
    case "galician":
        return .galician
    case "georgian":
        return .georgian
    case "german":
        return .german
    case "greek":
        return .greek
    case "gujarati":
        return .gujarati
    case "haitianCreole":
        return .haitianCreole
    case "hebrew":
        return .hebrew
    case "hindi":
        return .hindi
    case "hungarian":
        return .hungarian
    case "icelandic":
        return .icelandic
    case "indonesian":
        return .indonesian
    case "irish":
        return .irish
    case "italian":
        return .italian
    case "japanese":
        return .japanese
    case "kannada":
        return .kannada
    case "korean":
        return .korean
    case "latvian":
        return .latvian
    case "lithuanian":
        return .lithuanian
    case "macedonian":
        return .macedonian
    case "malay":
        return .malay
    case "maltese":
        return .maltese
    case "marathi":
        return .marathi
    case "norwegian":
        return .norwegian
    case "persian":
        return .persian
    case "polish":
        return .polish
    case "portuguese":
        return .portuguese
    case "romanian":
        return .romanian
    case "russian":
        return .russian
    case "slovak":
        return .slovak
    case "slovenian":
        return .slovenian
    case "spanish":
        return .spanish
    case "swahili":
        return .swahili
    case "tagalog":
        return .tagalog
    case "tamil":
        return .tamil
    case "telugu":
        return .telugu
    case "thai":
        return .thai
    case "turkish":
        return .turkish
    case "ukrainian":
        return .ukrainian
    case "urdu":
        return .urdu
    case "vietnamese":
        return .vietnamese
    case "welsh":
        return .welsh
    default:
        return nil
    }
}
